### ISSUE TITLE
Having to use fs.readFileSync to get it to detect file changes

### ISSUE THREAD

**Issue by nickjohngray** [wappsify/react-static-plugin-file-watch-reload#7]
I Like to start off saying this plugin is great! and works as expected

I Just wanted to report  to get it to listen for file changes of my json file i had to use fs like this

```javascript
const getManifest = async () =>
  JSON.parse( await fs.readFileSync(   path.resolve(process.cwd(), 'manifest.json'), 'utf8'))
```

using a standard import did not work.

I use that in my React.static config .
This file contains all the info for my website..
Am I using this the right way ?
[Here's a link to all the code ](https://github.com/nickjohngray/easyecom)

**Comment by wappsify** [comment]
Hey Nick,

this is actually not a problem related to the plugin - the plugin simply watches files and then calls the `rebuildRoutes` function of `react-static` when appropriate.

Instead, your problem lies with webpack - on startup of the `react-static` dev server, it creates a module for the imported JSON file. This however does not update when the JSON file does, which results in the behaviour you're seeing.

Your "workaround" of calling `fs.ReadFileSync`  in your `static.config.js` is exactly how to approach this problem. With this approach you guarantee that the file is read "fresh" every time `rebuildRoutes` is called.

Thank you! 💐 I will add a FAQ section in the README to answer this question for newcomers.
